"""add unique=True

Revision ID: 3055b8b64f18
Revises: fa45fadcf43f
Create Date: 2023-09-08 17:20:27.481473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3055b8b64f18'
down_revision: Union[str, None] = 'fa45fadcf43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Brand', ['brand_name'])
    op.create_unique_constraint(None, 'Category', ['category_name'])
    op.create_unique_constraint(None, 'User', ['password'])
    op.create_unique_constraint(None, 'User', ['email'])
    op.create_unique_constraint(None, 'User', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'Category', type_='unique')
    op.drop_constraint(None, 'Brand', type_='unique')
    # ### end Alembic commands ###
