"""add params for Product.product_name

Revision ID: b8086134d993
Revises: b51d0256161d
Create Date: 2023-09-13 20:22:47.055667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8086134d993'
down_revision: Union[str, None] = 'b51d0256161d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Product', sa.Column('img', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'Product', ['product_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Product', type_='unique')
    op.drop_column('Product', 'img')
    # ### end Alembic commands ###
